# Generated by Django 4.2.1 on 2023-06-07 07:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('drf_test_app', '0002_dish_tableware_delete_article_delete_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dish',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
