# Generated by Django 4.2.1 on 2023-06-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_test_app', '0003_dish_is_deleted_dish_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableware',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
